# Generated by Django 2.0.7 on 2023-12-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
